### ISSUE TITLE
NOT WORKING PROPERLY Please PLEASE PLEASE PLEASE HELP!!!!

### ISSUE THREAD

**Issue by ghost** [pirate/mac-hardware-toys#5]
Ok, I was running the `audio.py` file and got this...

```
$ python3 audio.py
[+] Starting...
Traceback (most recent call last):
  File "audio.py", line 46, in <module>
    runloop(stream)
  File "audio.py", line 35, in runloop
    data = stream.read(CHUNK)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9981] Input overflowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "audio.py", line 48, in <module>
    stream.stop_stream()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyaudio.py", line 524, in stop_stream
    pa.stop_stream(self._stream)
OSError: Stream not open

```

**Comment by pirate** [comment]
It ran out of buffer space, just quit and run it again.  The script isn't really designed to be run for hours at a time, it's just a novelty thing.

**Comment by ghost** [comment]
Thank you, I restarted my computer and it helped.
