### ISSUE TITLE
something wrong, after running a while

### ISSUE THREAD

**Issue by oit63** [pirate/mac-hardware-toys#9]
[+] Starting...
Traceback (most recent call last):
  File "audio.py", line 46, in <module>
    runloop(stream)
  File "audio.py", line 35, in runloop
    data = stream.read(CHUNK)
  File "/usr/local/lib/python3.6/site-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9981] Input overflowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "audio.py", line 48, in <module>
    stream.stop_stream()
  File "/usr/local/lib/python3.6/site-packages/pyaudio.py", line 524, in stop_stream
    pa.stop_stream(self._stream)
OSError: Stream not open

**Comment by oit63** [comment]
actually, I find that it crashed when switched to another song.

**Comment by pirate** [comment]
See https://github.com/pirate/mac-keyboard-brightness/issues/5
